name: b
recipe: backdrop
services:
  appserver:
    type: php:7.2
    webroot: backdrop
    build_as_root:
      # Make symlink for `b`.
      - ln -s /app/b.php /usr/local/bin/b
      # Setup Backdrop installations.
      - wget -q --show-progress https://github.com/backdrop/backdrop/archive/1.x.zip
      - unzip -q 1.x.zip && rm 1.x.zip
      - mv backdrop-1.x backdrop
      - echo 'if (isset($_SERVER["BACKDROP_SETTINGS"])) unset($_SERVER["BACKDROP_SETTINGS"]);' >> backdrop/settings.php
      - cp -r backdrop multisite
      # Download PHPUnit.
      - wget -q --show-progress -O phpunit https://phar.phpunit.de/phpunit-8.5.phar
      - chmod +x phpunit
    run:
      # Install normal Backdrop site.
      - cd backdrop && ./core/scripts/install.sh --account-pass=password --db-url=mysql://backdrop:backdrop@database/backdrop
  multisite:
    type: php:7.2
    webroot: multisite
    build_as_root:
      # Configure multisite installation.
      - echo '$sites["multi-1.lndo.site"] = "multi_one";' >> multisite/sites/sites.php
      - mkdir multisite/sites/multi_one && cp multisite/settings.php multisite/sites/multi_one/settings.php
      - echo '$sites["multi-2.lndo.site"] = "multi_two";' >> multisite/sites/sites.php
      - mkdir multisite/sites/multi_two && cp multisite/settings.php multisite/sites/multi_two/settings.php
    run:
      # Install Backdrop multisites.
      - cd multisite && ./core/scripts/install.sh --url=multi-1.lndo.site --account-pass=password --site-name="Multisite 1" --db-url=mysql://backdrop:backdrop@database/multi_one
      - cd multisite && ./core/scripts/install.sh --url=multi-2.lndo.site --account-pass=password --site-name="Multisite 2" --db-url=mysql://backdrop:backdrop@database/multi_two
  database:
    type: mariadb
    run_as_root:
      # Create additional databases (for multisites).
      - mysql -u root -e "CREATE DATABASE IF NOT EXISTS multi_one; GRANT ALL PRIVILEGES ON multi_one.* TO 'backdrop'@'%' IDENTIFIED by 'backdrop';"
      - mysql -u root -e "CREATE DATABASE IF NOT EXISTS multi_two; GRANT ALL PRIVILEGES ON multi_two.* TO 'backdrop'@'%' IDENTIFIED by 'backdrop';"
tooling:
  b:
    service: appserver
    cmd: b
  run-tests:
    service: appserver
    cmd:
      - cd /app/backdrop && /app/phpunit --testsuite backdrop --configuration /app/tests
      - cd /app/multisite && /app/phpunit --testsuite multisite --configuration /app/tests
  # check-code:
  #   service: appserver
  #   cmd: /app/b/vendor/bin/phpcs --standard=/app/b/vendor/backdrop/coder/coder_sniffer/Backdrop --ignore=vendor/* /app/b
proxy:
  appserver:
    - b.lndo.site
  multisite:
    - multi-1.lndo.site
    - multi-2.lndo.site
